### ISSUE TITLE
Consider Co-authorship Metrics

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#10]
"I support grant proposal development, and sometimes center grants require that a show of collaboration through co-authorship be included for members of a center. I have been researching the various bibliometric options/tools and haven’t found anything that seems to cater to this situation. I am wondering if you are aware of tools available to do what I am describing (that I have not yet happened upon). Thank you in advance for any light that you can shed."

**Comment by rchampieux** [comment]
Possible post/approaches:
* Proportion based measures of collaboration (as reflected in SciVal, for example).
* Mean based

Could be one post that speaks to all types of collaboration calculations, or we could group by the different approaches.

**Comment by rchampieux** [comment]
## Suggested approach

**Object Level**:  Author
Me

**Comment by rchampieux** [comment]
@coateshl and @skonkiel please review and comment before our next sprint.

**Comment by skonkiel** [comment]
This seems to be missing the "Appropriate Uses" and "Inappropriate Uses" section, the former of which I think is important to point out that people often use co-authorship as a proxy for a researcher's collaboration practices. In fact, I'd incorporate that information into the Definition itself (because that's why people use it).

> Metric Definition: The percentage or proportion of an author's publications with at least one co-author from a specific category of contributors, such as those from another institution or county. **Co-authorship is often used as a proxy understanding a researcher's collaborative practices.**

On the mean vs proportion approach you ask about: I think I'll need to see the draft text for the  Calculation section to be sure, but it's my understanding that proportion is what's most commonly used. We should probably also ask around.

**Comment by coateshl** [comment]
@skonkiel Robin & I discussed today; she will proceed with developing the full post

**Comment by rchampieux** [comment]
Rodrigo - new editorial board member - will take this one on, so closing the issue.
